# Generated by Django 6.0.5 on 2026-05-25 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frequencias', '0001_initial'),
        ('professores', '0001_initial'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='professores.professor'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='turmas.turma'),
        ),
        migrations.AlterUniqueTogether(
            name='frequencia',
            unique_together={('aluno', 'turma', 'data')},
        ),
    ]
