# Generated by Django 6.0.5 on 2026-05-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('ano', models.PositiveIntegerField()),
                ('disciplinas', models.ManyToManyField(related_name='grades_curriculares', to='disciplinas.disciplina')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
