# Generated by Django 5.2.14 on 2026-05-29 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_gradecurricular_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradecurricular',
            options={'ordering': ['-created_at']},
        ),
    ]
