# Generated by Django 6.0.5 on 2026-05-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, max_length=1000, null=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_avaliacao', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
