# Generated by Django 5.2.14 on 2026-05-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
