# Generated by Django 5.2.14 on 2026-05-29 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0003_alter_avaliacao_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['-created_at']},
        ),
    ]
