# Generated by Django 5.2.14 on 2026-05-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0004_alter_avaliacao_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
