# Generated by Django 5.2.14 on 2026-05-29 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_alter_aluno_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['-created_at']},
        ),
    ]
